export const TASKS_MOCK = [
  {
    id: 1,
    title: 'Air Conditioning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: true,
  },
  {
    id: 2,
    title: 'Couch Cleaning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: false,
  },
  {
    id: 3,
    title: 'Air Conditioning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: true,
  },
  {
    id: 4,
    title: 'Couch Cleaning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: false,
  },
  {
    id: 5,
    title: 'Air Conditioning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: true,
  },
  {
    id: 6,
    title: 'Couch Cleaning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: false,
  },
  {
    id: 7,
    title: 'Air Conditioning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: true,
  },
  {
    id: 8,
    title: 'Couch Cleaning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: false,
  },
  {
    id: 9,
    title: 'Air Conditioning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: true,
  },
  {
    id: 10,
    title: 'Couch Cleaning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: false,
  },
  {
    id: 11,
    title: 'Air Conditioning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: true,
  },
  {
    id: 12,
    title: 'Couch Cleaning',
    createdAt: '13 Jun,2024',
    duration: '37 Hr 20 Min 12 Sec',
    isMaintenance: false,
  },
];
